GET http://localhost:3000/lessons
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTc1MjY0MS0xMzJiLTRlYzMtYWI2Ny1iYjIxMTZjYzNjOTQiLCJyb2xlIjoiVFJBSU5FUiIsImlhdCI6MTczNzAxOTk2MSwiZXhwIjoxNzM4MjI5NTYxfQ.9AOmAuH4COhzJsVnkYwKZB8upv5euP13jcDz_F9nt4E
