name: CI/CD Pipeline # 워크플로우의 이름을 'CI/CD Pipeline'으로 설정

on: # 워크플로우 트리거 조건 설정
  push: # Git push 이벤트 발생 시 실행
    branches: ["dev"] # dev 브랜치에 push가 발생했을 때만 실행

jobs: # 실행할 작업들을 정의하는 섹션
  build-and-deploy: # 작업 이름을 'build-and-deploy'로 설정
    runs-on: ubuntu-latest # Ubuntu 최신 버전의 러너에서 작업 실행

    steps: # 작업의 세부 단계들을 정의
      - name: Checkout code # 코드 체크아웃 단계
        uses: actions/checkout@v3 # GitHub 저장소 코드를 가져오는 공식 액션 사용

      - name: Build Docker image # Docker 이미지 빌드 단계
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin  # Docker Hub 로그인 (보안을 위해 secrets 사용)
          docker --version
          sleep 3
          docker build \
            --build-arg "NEXT_PUBLIC_API_URL=https://fitmate-be.asia" \
            --build-arg "NODE_ENV=production" \
            --build-arg "NEXT_PUBLIC_KAKAO_API_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_API_KEY }}" \
            -t kipid/fitmate-fe:v0.2 . || exit 1  # Dockerfile을 사용하여 이미지 빌드, 태그는 v0.2로 지정
          sleep 3
          docker push kipid/fitmate-fe:v0.2  # 빌드된 이미지를 Docker Hub에 업로드
          sleep 3
          docker logout
        continue-on-error: false

      - name: Deploy to server # 서버 배포 단계
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            docker pull kipid/fitmate-fe:v0.2  # 최신 이미지 다운로드
            docker stop $(docker ps -a -q) || true
            docker rm -f $(docker ps -a -q) || true
            docker stop fitmate-fe-container || true  # 기존 컨테이너 중지 (실패해도 계속 진행)
            docker rm fitmate-fe-container || true  # 기존 컨테이너 제거 (실패해도 계속 진행)
            docker run -d -p 3001:3001 --name fitmate-fe-container \
              -e "NEXT_PUBLIC_API_URL=https://fitmate-be.asia" \
              -e "NODE_ENV=production" \
              -e "NEXT_PUBLIC_KAKAO_API_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_API_KEY }}" \
              kipid/fitmate-fe:v0.2
            sleep 5  # 컨테이너 실행 안정화 대기
            docker system prune -f  # 사용하지 않는 Docker 리소스 정리
            sleep 3
            ps -ef | grep docker  # Check running processes
            docker logout
